name: Run Tests On Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.11.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          echo requirements installed
          pip uninstall bson
          pip uninstall pymongo
          pip install pymongo
      - name: Run tests
        run: |
          cd tests
          python -m unittest test
